[package]
name = "nekoguard-certd"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["server", "tokio", "http1"] }
http-body-util = "0.1"
bytes = "1"
rustls-acme = { version = "0.15.4", default-features = false, features = ["tokio", "ring", "tls12", "webpki-roots"] }
rustls = "0.23.43"
tokio-rustls = "0.26.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1.4"
log = "0.4.34"
env_logger = "0.11"
futures = "0.3.34"
rand = { version = "0.8", features = ["alloc"] }
redis = { version = "1.6.0", features = ["tokio-comp", "connection-manager"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
