apiVersion: v1
kind: ConfigMap
metadata:
  name: nekoguard-config
  namespace: nekoguard
data:
  nekoguard.toml: |
    domains = ["root-workspace.net"]
    redis_url = "redis://redis:6379"
    contact_email = "you@example.com"
    cloudflare_api_token = ""
    cloudflare_zone_id = ""

    [nekoguard]
    port = 443

    [nekoguard.session]
    ttl = 1800

    [nekoguard.rate_limit]
    enabled = true
    rps = 10

    [nekoguard.log]
    level = "info"
    requests = true

    [[nekoguard.sites]]
    domain = "root-workspace.net"
    upstream = "http://10.1.3.16:2283"

    [certd]
    port = 8443
    renewal_interval = 86400
