apiVersion: v1
kind: Secret
metadata:
  name: nekoguard
  namespace: nekoguard
type: Opaque
stringData:
  cloudflare_api_token: "REPLACE_WITH_YOUR_TOKEN"
  cloudflare_zone_id: "REPLACE_WITH_YOUR_ZONE_ID"
